import { NextResponse } from "next/server";

export function GET() {
  return NextResponse.json({
    authentication: "Authorization: Bearer AI_INGEST_TOKEN",
    endpoints: {
      createOrDraft: "POST /api/ingest",
      uploadMedia: "POST /api/ingest/upload (multipart: file, appSlug)",
    },
    actions: {
      create_app: { name: "string", slug: "kebab-case", tagline: "optional", description: "optional", links: [{ label: "Website", url: "https://..." }] },
      create_update: { appSlug: "existing-app-slug", title: "string", description: "optional", status: "planning|building|testing|shipped", version: "optional", tags: ["release", "android"], scheduledFor: "optional ISO-8601 date", media: ["https://res.cloudinary.com/..."], isPublished: true },
      draft_copy: { appName: "string", context: "release notes or rough notes", tone: "optional" },
    },
    note: "created_at is always generated by the server. Do not send user API credentials from a browser.",
  });
}
